// Coach-voice player. Plays pre-rendered clips from /coach/ (generated by
// scripts/gen-coach-voice.mjs). If no voice pack is installed it stays silent —
// the whole feature is a graceful no-op until clips + manifest.json exist.
//
// Every "speak" returns a Promise<boolean> that resolves true only if audio
// actually played to the end. Callers (CoachedSession) await this so a drill
// never starts on top of the coach still talking (no overlap), and can fall
// back to a silent visual countdown when the voice is off/unavailable.

type CoachEvent =
  | 'up-next'
  | 'rest-start'
  | 'rest-tip'
  | 'done'
  | 'session'
  | 'name-lead'
  | 'count-in';

interface Manifest {
  counts: Record<string, number>;
  names: string[]; // slugs that have a name-<slug>.mp3
}

const STORAGE_KEY = 'daily-fret-coach-voice';

let manifest: Manifest | null = null;
let manifestPromise: Promise<void> | null = null;
const lastIdx: Record<string, number> = {}; // event -> last index, to avoid immediate repeats

// Serial playback core. Exactly one clip is ever audible: every clip runs
// through a promise queue so lines never overlap. A generation counter lets a
// hard interrupt (stopVoice, or an interrupting `speak`) invalidate anything
// still queued or in flight, so a stale fire-and-forget line (a drill's "done",
// a rest tip) can't jump in on top of a newer sequence. This is what prevents
// the "voices stack up / play late over each other" failure when drills, rests
// and count-ins fire close together.
let current: HTMLAudioElement | null = null;
let currentFinish: ((ok: boolean) => void) | null = null;
let queueTail: Promise<void> = Promise.resolve();
let generation = 0;

function readEnabled(): boolean {
  try {
    return localStorage.getItem(STORAGE_KEY) !== '0';
  } catch {
    return true;
  }
}

let enabled = readEnabled();

export function isCoachVoiceEnabled(): boolean {
  return enabled;
}

export function setCoachVoiceEnabled(value: boolean): void {
  enabled = value;
  try {
    localStorage.setItem(STORAGE_KEY, value ? '1' : '0');
  } catch {
    /* ignore */
  }
  if (!value) stopVoice();
}

function base(): string {
  // Respect Vite's base path; defaults to '/'.
  return import.meta.env.BASE_URL ?? '/';
}

// Must match scripts/slugify.mjs exactly so a drill title maps to its clip.
function slugify(s: string): string {
  return s
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

async function loadManifest(): Promise<void> {
  if (manifestPromise) return manifestPromise;
  manifestPromise = (async () => {
    try {
      const res = await fetch(`${base()}coach/manifest.json`, { cache: 'force-cache' });
      if (!res.ok) return;
      const raw = await res.json();
      // Tolerate both the structured shape and a legacy flat counts map.
      manifest = raw && raw.counts
        ? { counts: raw.counts, names: raw.names ?? [] }
        : { counts: raw ?? {}, names: raw?.names ?? [] };
    } catch {
      manifest = null; // no voice pack installed yet
    }
  })();
  return manifestPromise;
}

// Warm the manifest early (e.g. when a coached session mounts) so the first
// line plays without a fetch delay.
export function preloadCoachVoice(): void {
  void loadManifest().then(() => {
    if (!manifest) return;
    // Warm the HTTP cache for every clip we might play this session (drill-name
    // clips plus each event variant), so the first time a line is needed it
    // plays immediately instead of stalling on a cold fetch — a cold fetch is
    // what made lines occasionally "not play" or arrive late.
    const warm = (url: string) => void fetch(url, { cache: 'force-cache' }).catch(() => {});
    for (const slug of manifest.names) warm(`${base()}coach/name-${slug}.mp3`);
    for (const [event, count] of Object.entries(manifest.counts)) {
      for (let i = 1; i <= count; i++) warm(`${base()}coach/${event}-${pad(i)}.mp3`);
    }
  });
}

const pad = (n: number) => String(n).padStart(2, '0');

function pickIndex(event: string, count: number): number {
  if (count <= 1) return 1;
  let idx = 1 + Math.floor(Math.random() * count);
  if (idx === lastIdx[event]) idx = (idx % count) + 1; // nudge off an immediate repeat
  lastIdx[event] = idx;
  return idx;
}

// Stop the clip that's playing right now (if any) and resolve its awaiter as
// false, so a chained sequence never hangs on a line we cut off.
function stopCurrent(): void {
  const audio = current;
  const finish = currentFinish;
  current = null;
  currentFinish = null;
  if (audio) {
    audio.onended = null;
    audio.onerror = null;
    audio.pause();
    audio.src = '';
  }
  if (finish) finish(false);
}

export function stopVoice(): void {
  generation += 1; // invalidate everything still queued or in flight
  queueTail = Promise.resolve();
  stopCurrent();
}

// Play a single clip to completion. Resolves true on 'ended', false on
// error/abort. Only ever one of these is live at a time (see the queue below).
function playClip(url: string): Promise<boolean> {
  return new Promise((resolve) => {
    let audio: HTMLAudioElement;
    try {
      audio = new Audio(url);
    } catch {
      resolve(false);
      return;
    }
    audio.volume = 0.95;
    const finish = (ok: boolean) => {
      if (current === audio) {
        current = null;
        currentFinish = null;
      }
      audio.onended = null;
      audio.onerror = null;
      resolve(ok);
    };
    current = audio;
    currentFinish = finish;
    audio.onended = () => finish(true);
    audio.onerror = () => finish(false);
    audio.play().catch(() => finish(false));
  });
}

// Queue a clip. interrupt=true (default) stops anything playing/queued and plays
// now; interrupt=false appends so it plays seamlessly after the current clip,
// never on top of it. Resolves true only if the clip actually reached its end.
function playUrl(url: string, interrupt = true): Promise<boolean> {
  if (interrupt) stopVoice();
  const myGen = generation;
  const started = queueTail.then(() => (myGen === generation ? playClip(url) : false));
  // Keep the tail a never-rejecting void chain so the next clip always waits for
  // this one, whatever it resolves to.
  queueTail = started.then(
    () => undefined,
    () => undefined,
  );
  return started;
}

// Speak one variant of an event. Resolves true only if a clip actually played.
export async function speak(event: CoachEvent, interrupt = true): Promise<boolean> {
  if (!enabled) return false;
  await loadManifest();
  const count = manifest?.counts[event];
  if (!count) return false;
  const idx = pickIndex(event, count);
  return playUrl(`${base()}coach/${event}-${pad(idx)}.mp3`, interrupt);
}

// Announce the upcoming drill by name when a clip exists, e.g. "Up next," +
// "<drill name>". Falls back to a generic line (same voice) for titles we have
// no name clip for. Resolves true if anything was spoken.
export async function announceDrill(title: string): Promise<boolean> {
  if (!enabled) return false;
  await loadManifest();
  if (!manifest) return false;
  const slug = slugify(title);
  if (slug && manifest.names.includes(slug) && manifest.counts['name-lead']) {
    await speak('name-lead'); // "Up next," — interrupts anything still playing
    if (!enabled) return false; // muted mid lead-in — don't fire the name clip
    return playUrl(`${base()}coach/name-${slug}.mp3`, false); // …the name, seamless
  }
  return speak('up-next'); // generic, in-voice fallback
}
