// Coach-voice player. Plays pre-rendered clips from /coach/ (generated by
// scripts/gen-coach-voice.mjs). If no voice pack is installed it stays silent —
// the whole feature is a graceful no-op until clips + manifest.json exist.
//
// Every "speak" returns a Promise<boolean> that resolves true only if audio
// actually played to the end. Callers (CoachedSession) await this so a drill
// never starts on top of the coach still talking (no overlap), and can fall
// back to a silent visual countdown when the voice is off/unavailable.

type CoachEvent =
  | 'up-next'
  | 'rest-start'
  | 'rest-tip'
  | 'done'
  | 'session'
  | 'name-lead'
  | 'count-in';

interface Manifest {
  counts: Record<string, number>;
  names: string[]; // slugs that have a name-<slug>.mp3
}

const STORAGE_KEY = 'daily-fret-coach-voice';

let manifest: Manifest | null = null;
let manifestPromise: Promise<void> | null = null;
const lastIdx: Record<string, number> = {}; // event -> last index, to avoid immediate repeats
let current: HTMLAudioElement | null = null;
let currentSettle: ((ok: boolean) => void) | null = null;

function readEnabled(): boolean {
  try {
    return localStorage.getItem(STORAGE_KEY) !== '0';
  } catch {
    return true;
  }
}

let enabled = readEnabled();

export function isCoachVoiceEnabled(): boolean {
  return enabled;
}

export function setCoachVoiceEnabled(value: boolean): void {
  enabled = value;
  try {
    localStorage.setItem(STORAGE_KEY, value ? '1' : '0');
  } catch {
    /* ignore */
  }
  if (!value) stopVoice();
}

function base(): string {
  // Respect Vite's base path; defaults to '/'.
  return import.meta.env.BASE_URL ?? '/';
}

// Must match scripts/slugify.mjs exactly so a drill title maps to its clip.
function slugify(s: string): string {
  return s
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

async function loadManifest(): Promise<void> {
  if (manifestPromise) return manifestPromise;
  manifestPromise = (async () => {
    try {
      const res = await fetch(`${base()}coach/manifest.json`, { cache: 'force-cache' });
      if (!res.ok) return;
      const raw = await res.json();
      // Tolerate both the structured shape and a legacy flat counts map.
      manifest = raw && raw.counts
        ? { counts: raw.counts, names: raw.names ?? [] }
        : { counts: raw ?? {}, names: raw?.names ?? [] };
    } catch {
      manifest = null; // no voice pack installed yet
    }
  })();
  return manifestPromise;
}

// Warm the manifest early (e.g. when a coached session mounts) so the first
// line plays without a fetch delay.
export function preloadCoachVoice(): void {
  void loadManifest();
}

const pad = (n: number) => String(n).padStart(2, '0');

function pickIndex(event: string, count: number): number {
  if (count <= 1) return 1;
  let idx = 1 + Math.floor(Math.random() * count);
  if (idx === lastIdx[event]) idx = (idx % count) + 1; // nudge off an immediate repeat
  lastIdx[event] = idx;
  return idx;
}

export function stopVoice(): void {
  if (current) {
    current.pause();
    current = null;
  }
  // Resolve any awaiter so a chained intro sequence doesn't stall on a clip we
  // just cut off (e.g. the user muted or closed mid-line).
  if (currentSettle) {
    const settle = currentSettle;
    currentSettle = null;
    settle(false);
  }
}

// Play one URL to completion. Resolves true on 'ended', false on error/abort.
function playUrl(url: string, interrupt = true): Promise<boolean> {
  return new Promise((resolve) => {
    try {
      if (interrupt) stopVoice();
      const audio = new Audio(url);
      audio.volume = 0.95;
      current = audio;
      currentSettle = resolve;
      const done = (ok: boolean) => {
        if (current === audio) current = null;
        if (currentSettle === resolve) currentSettle = null;
        resolve(ok);
      };
      audio.addEventListener('ended', () => done(true), { once: true });
      audio.addEventListener('error', () => done(false), { once: true });
      audio.play().catch(() => done(false));
    } catch {
      resolve(false);
    }
  });
}

// Speak one variant of an event. Resolves true only if a clip actually played.
export async function speak(event: CoachEvent, interrupt = true): Promise<boolean> {
  if (!enabled) return false;
  await loadManifest();
  const count = manifest?.counts[event];
  if (!count) return false;
  const idx = pickIndex(event, count);
  return playUrl(`${base()}coach/${event}-${pad(idx)}.mp3`, interrupt);
}

// Announce the upcoming drill by name when a clip exists, e.g. "Up next," +
// "<drill name>". Falls back to a generic line (same voice) for titles we have
// no name clip for. Resolves true if anything was spoken.
export async function announceDrill(title: string): Promise<boolean> {
  if (!enabled) return false;
  await loadManifest();
  if (!manifest) return false;
  const slug = slugify(title);
  if (slug && manifest.names.includes(slug) && manifest.counts['name-lead']) {
    await speak('name-lead'); // "Up next," — interrupts anything still playing
    if (!enabled) return false; // muted mid lead-in — don't fire the name clip
    return playUrl(`${base()}coach/name-${slug}.mp3`, false); // …the name, seamless
  }
  return speak('up-next'); // generic, in-voice fallback
}
