// Coach-voice player. Plays pre-rendered clips from /coach/ (generated by
// scripts/gen-coach-voice.mjs). If no voice pack is installed it stays silent —
// the whole feature is a graceful no-op until clips + manifest.json exist.

type CoachEvent = 'up-next' | 'rest-start' | 'rest-tip' | 'done' | 'session';

const STORAGE_KEY = 'daily-fret-coach-voice';

let manifest: Record<string, number> | null = null;
let manifestPromise: Promise<void> | null = null;
const lastIdx: Record<string, number> = {}; // event -> last index, to avoid immediate repeats
let current: HTMLAudioElement | null = null;

function readEnabled(): boolean {
  try {
    return localStorage.getItem(STORAGE_KEY) !== '0';
  } catch {
    return true;
  }
}

let enabled = readEnabled();

export function isCoachVoiceEnabled(): boolean {
  return enabled;
}

export function setCoachVoiceEnabled(value: boolean): void {
  enabled = value;
  try {
    localStorage.setItem(STORAGE_KEY, value ? '1' : '0');
  } catch {
    /* ignore */
  }
  if (!value) stopVoice();
}

function base(): string {
  // Respect Vite's base path; defaults to '/'.
  return import.meta.env.BASE_URL ?? '/';
}

async function loadManifest(): Promise<void> {
  if (manifestPromise) return manifestPromise;
  manifestPromise = (async () => {
    try {
      const res = await fetch(`${base()}coach/manifest.json`, { cache: 'force-cache' });
      if (res.ok) manifest = await res.json();
    } catch {
      manifest = null; // no voice pack installed yet
    }
  })();
  return manifestPromise;
}

// Warm the manifest early (e.g. when a coached session mounts) so the first
// line plays without a fetch delay.
export function preloadCoachVoice(): void {
  void loadManifest();
}

const pad = (n: number) => String(n).padStart(2, '0');

function pickIndex(event: string, count: number): number {
  if (count <= 1) return 1;
  let idx = 1 + Math.floor(Math.random() * count);
  if (idx === lastIdx[event]) idx = (idx % count) + 1; // nudge off an immediate repeat
  lastIdx[event] = idx;
  return idx;
}

export function stopVoice(): void {
  if (current) {
    current.pause();
    current = null;
  }
}

// Speak one variant of an event. Safe to call anytime: silent if disabled or no
// pack. `interrupt` (default true) stops any line still playing.
export async function speak(event: CoachEvent, interrupt = true): Promise<void> {
  if (!enabled) return;
  await loadManifest();
  const count = manifest?.[event];
  if (!count) return;
  const idx = pickIndex(event, count);
  const url = `${base()}coach/${event}-${pad(idx)}.mp3`;
  try {
    if (interrupt) stopVoice();
    const audio = new Audio(url);
    audio.volume = 0.95;
    current = audio;
    audio.addEventListener('ended', () => {
      if (current === audio) current = null;
    });
    await audio.play().catch(() => {});
  } catch {
    /* autoplay blocked or load error — stay silent */
  }
}
