// Canonical coach phrase bank — the single source of truth for the voice clips.
// `scripts/gen-coach-voice.mjs` reads this to synthesize one MP3 per line.
// `coach-voice-script.html` mirrors these for the manual copy/paste route.
//
// `file` is the clip prefix; clips are written as `<file>-NN.mp3` (1-based).
// These prefixes are also the event names the in-app player calls (see
// src/audio/coachVoice.ts): up-next, rest-start, rest-tip, done, session.

export const SECTIONS = [
  {
    file: 'up-next',
    title: 'Up Next — drill intro',
    lines: [
      "Alright, here's your next one. Let's lock in.",
      "Up next — settle in and find your hands.",
      "Next drill coming up. Take a breath and get ready.",
      "Here we go again. Eyes on the screen, you've got this.",
      "Time for the next one. Loose shoulders, steady hands.",
      "Let's keep the momentum going. Next drill.",
      "Coming up next. Reset, refocus, and let's play.",
      "Your next challenge is ready. Trust your fingers.",
      "Next up. Small steps, big progress.",
      "Let's go. Get your hands into position.",
      "Here's the next one. Stay smooth, stay relaxed.",
      "Ready for the next? Let's make it count.",
      "Onward to the next drill. Breathe, and begin.",
      "Next one's loaded. Find your groove.",
    ],
  },
  {
    file: 'rest-start',
    title: 'Rest — starting',
    lines: [
      "Nice work. Take a moment to rest.",
      "That's done. Relax for a few seconds.",
      "Good effort. Shake it out and breathe.",
      "Rest up. Let your hands recover.",
      "Take a breather, you earned it.",
      "Ease off for a moment. Loosen those fingers.",
      "Pause and reset. We'll go again shortly.",
      "Great. Drop your shoulders and relax.",
      "Quick rest now. Let the tension melt away.",
      "Catch your breath. The next one will be ready soon.",
      "Rest those hands. Stretch if you need to.",
      "Well played. Take a short break.",
      "Breathe out. Let everything soften for a second.",
      "Time to recover. Stay loose.",
    ],
  },
  {
    file: 'rest-tip',
    title: 'Rest — tips & encouragement',
    lines: [
      "Gently stretch your fingers and wrists.",
      "Roll your shoulders back and let them drop.",
      "Shake out your fretting hand.",
      "Take a slow breath in… and out.",
      "Wiggle your fingers to keep the blood flowing.",
      "Loosen your grip. Tension is the enemy.",
      "Sip some water if you've got it.",
      "Open and close your hands a few times.",
      "Relax your jaw and your shoulders.",
      "Stretch your wrist gently, both directions.",
      "Picture the next chord shapes in your mind.",
      "Stay loose, and get ready for what's next.",
      "Give your hands a quick massage.",
      "Reset your posture, and sit tall.",
    ],
  },
  {
    file: 'done',
    title: 'Completion — after a drill/block',
    lines: [
      "Nicely done.",
      "That's the way. Clean work.",
      "Great job on that one.",
      "You're getting smoother every rep.",
      "Solid. That's real progress.",
      "Well played. Keep that up.",
      "Good control there.",
      "That's improvement you can feel.",
      "Excellent. Your hands are learning.",
      "Strong effort on that drill.",
      "Smooth and steady. Love it.",
      "That's how it's done.",
      "Nice. You're building real muscle memory.",
      "Good work. Onward.",
    ],
  },
  {
    file: 'name-lead',
    title: 'Lead-in before a spoken drill name',
    lines: [
      "Up next,",
      "Next up,",
      "Now,",
      "Here we go with,",
      "Time for,",
      "Let's do,",
    ],
  },
  {
    file: 'count-in',
    title: 'Count-in — spoken right before a drill starts',
    lines: [
      "Get ready… three, two, one.",
      "Here we go in three, two, one.",
      "Ready? And… go.",
      "Hands up… three, two, one.",
      "Let's play in three, two, one.",
      "Okay — three, two, one.",
    ],
  },
  {
    file: 'session',
    title: 'Session complete — final congrats',
    lines: [
      "That's a wrap. You finished today's session. Be proud.",
      "Session complete. Every minute today made you better.",
      "You did it. Consistency like this is how players are made.",
      "All done for today. Your future self thanks you.",
      "Congratulations. A full session, in the books.",
      "That's everything. Great discipline showing up today.",
      "Session finished. Rest those hands, you earned it.",
      "Beautifully done. See you tomorrow for more.",
      "You made it through. Small steps, every single day.",
      "Complete. That's another brick in the wall of mastery.",
      "Well done today. Real progress, real effort.",
      "That's the session. Now keep this streak alive.",
      "Finished strong. Be proud of the work you put in.",
      "All wrapped up. Your fingers are stronger than yesterday.",
    ],
  },
];
